spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board_project?useSSL=false&useUnicode=true&character_set_server=utf8mb4&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    hibernate:
      ddl-auto: validate